databases:
  - name: cba-portal-db
    plan: free
    databaseName: cba_portal
    user: cba_admin

services:
  - type: web
    name: cba-portal-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cba-portal-db
          property: connectionString
      - key: DB_TYPE
        value: postgresql
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://cba-portal-frontend.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: .jpg,.jpeg,.png,.pdf,.doc,.docx,.xls,.xlsx

  - type: web
    name: cba-portal-frontend
    env: static
    plan: free
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /fixed-frontend.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff